### ISSUE TITLE
How to add an ID and resolver to wikidata items

### ISSUE THREAD

**Issue by nickdickinson** [WASHNote/WASHWeb#20]

**Comment by nickdickinson** [comment]
So one thing to think about related to this is how to do the opposite as well. If we aim to ask WASH sector organization to keep their wikidata entries up to date, then we can also ask them to tag it with the right property to ensure we know they are a WASH sector organization, even if they are not in the registry (with an ID), they will have a code on wikidata.

**Comment by nickdickinson** [comment]
See: https://www.wikidata.org/wiki/Wikidata:Data_donation

**Comment by decentral1se** [comment]
Consolidating to https://github.com/WASHNote/WASHWeb/issues/26.
